# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'Boiler Bag' do
pod 'Firebase/Analytics'
pod 'Firebase/Auth'
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Boiler Bag

  target 'Boiler BagTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Boiler BagUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
